// Note to self: Generated by Gemini

#include <iostream>
#include <fstream>
#include <random>
#include <iomanip>
#include <string>

// Function to print usage instructions
void print_usage(const std::string& appName) {
    std::cerr << "Usage: " << appName << " <Number_of_Lines_N> <Dimension_D>\n";
    std::cerr << "Example: " << appName << " 100 5\n";
}

int main(int argc, char* argv[]) {
    // 1. Handle command-line arguments
    if (argc != 3) {
        print_usage(argv[0]);
        return 1;
    }

    // Convert arguments from string to integer
    int N; // Number of lines (points)
    int D; // Dimension (coordinates per line)

    try {
        N = std::stoi(argv[1]);
        D = std::stoi(argv[2]);
    } catch (const std::invalid_argument& e) {
        std::cerr << "Error: N and D must be integers.\n";
        print_usage(argv[0]);
        return 1;
    } catch (const std::out_of_range& e) {
        std::cerr << "Error: N or D is out of range.\n";
        return 1;
    }

    if (N <= 0 || D <= 0) {
        std::cerr << "Error: N and D must be positive integers.\n";
        return 1;
    }

    const std::string outputFilename = "random_data.txt";
    
    // 2. Setup file stream for writing
    std::ofstream outFile(outputFilename);

    if (!outFile.is_open()) {
        std::cerr << "Error: Could not open the file '" << outputFilename << "' for writing.\n";
        return 1;
    }

    // 3. Setup random number generation
    // Use the system clock as a seed for better randomness
    std::random_device rd;
    std::mt19937 generator(rd());
    
    // Define the distribution: uniform float between 0.0 and 1.0
    // std::uniform_real_distribution<float> is used for float values
    std::uniform_real_distribution<float> distribution(0.0f, 1.0f);

    // Set output precision for the float values
    outFile << std::fixed << std::setprecision(6);

    std::cout << "Generating " << N << " lines of " << D << " random floats in '" 
              << outputFilename << "'...\n";

    // 4. Generate and write the data
    for (int i = 0; i < N; ++i) {
        for (int j = 0; j < D; ++j) {
            float random_value = distribution(generator);
            outFile << random_value;

            // Separate coordinates with a space, but not after the last coordinate
            if (j < D - 1) {
                outFile << " ";
            }
        }
        // End the line after all D coordinates are written
        outFile << "\n";
    }

    // 5. Close the file and confirm
    outFile.close();
    std::cout << "Generation complete. File saved as '" << outputFilename << "'.\n";

    return 0;
}
